import type { Model } from '../types.js';

export const modelsDev = [
  {
    id: "alibaba:qwen3-coder-plus",
    provider: "alibaba",
    vendorId: "qwen3-coder-plus",
    displayName: "Qwen3 Coder Plus",
    family: "qwen3-coder-plus",
    status: "stable",
    context: {"combinedMax":1048576,"outputMax":65536},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":1,"outputPerMTokens":5},
    pricingSource: "models.dev",
    aliases: ["alibaba/qwen3-coder-plus"],
    releasedAt: "2025-07-23",
    source: "https://www.alibabacloud.com/help/en/model-studio/models",
    contextSource: "https://www.alibabacloud.com/help/en/model-studio/models",
    verifiedAt: "2025-07-23",
  },
  {
    id: "anthropic:claude-3-5-haiku-20241022",
    provider: "anthropic",
    vendorId: "claude-3-5-haiku-20241022",
    displayName: "Claude Haiku 3.5",
    family: "claude-3-5-haiku-20241022",
    status: "stable",
    context: {"combinedMax":200000,"outputMax":8192},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":0.8,"outputPerMTokens":4},
    pricingSource: "models.dev",
    aliases: ["anthropic/claude-3-5-haiku-20241022"],
    releasedAt: "2024-10-22",
    source: "https://docs.anthropic.com/en/docs/about-claude/models",
    contextSource: "https://docs.anthropic.com/en/docs/about-claude/models",
    verifiedAt: "2024-10-22",
  },
  {
    id: "anthropic:claude-3-5-sonnet-20240620",
    provider: "anthropic",
    vendorId: "claude-3-5-sonnet-20240620",
    displayName: "Claude Sonnet 3.5",
    family: "claude-3-5-sonnet-20240620",
    status: "stable",
    context: {"combinedMax":200000,"outputMax":8192},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":3,"outputPerMTokens":15},
    pricingSource: "models.dev",
    aliases: ["anthropic/claude-3-5-sonnet-20240620"],
    releasedAt: "2024-06-20",
    source: "https://docs.anthropic.com/en/docs/about-claude/models",
    contextSource: "https://docs.anthropic.com/en/docs/about-claude/models",
    verifiedAt: "2024-06-20",
  },
  {
    id: "anthropic:claude-3-5-sonnet-20241022",
    provider: "anthropic",
    vendorId: "claude-3-5-sonnet-20241022",
    displayName: "Claude Sonnet 3.5 v2",
    family: "claude-3-5-sonnet-20241022",
    status: "stable",
    context: {"combinedMax":200000,"outputMax":8192},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":3,"outputPerMTokens":15},
    pricingSource: "models.dev",
    aliases: ["anthropic/claude-3-5-sonnet-20241022"],
    releasedAt: "2024-10-22",
    source: "https://docs.anthropic.com/en/docs/about-claude/models",
    contextSource: "https://docs.anthropic.com/en/docs/about-claude/models",
    verifiedAt: "2024-10-22",
  },
  {
    id: "anthropic:claude-3-7-sonnet-20250219",
    provider: "anthropic",
    vendorId: "claude-3-7-sonnet-20250219",
    displayName: "Claude Sonnet 3.7",
    family: "claude-3-7-sonnet-20250219",
    status: "stable",
    context: {"combinedMax":200000,"outputMax":64000},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":3,"outputPerMTokens":15},
    pricingSource: "models.dev",
    aliases: ["anthropic/claude-3-7-sonnet-20250219"],
    releasedAt: "2025-02-19",
    source: "https://docs.anthropic.com/en/docs/about-claude/models",
    contextSource: "https://docs.anthropic.com/en/docs/about-claude/models",
    verifiedAt: "2025-02-19",
  },
  {
    id: "anthropic:claude-3-haiku-20240307",
    provider: "anthropic",
    vendorId: "claude-3-haiku-20240307",
    displayName: "Claude Haiku 3",
    family: "claude-3-haiku-20240307",
    status: "stable",
    context: {"combinedMax":200000,"outputMax":4096},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":0.25,"outputPerMTokens":1.25},
    pricingSource: "models.dev",
    aliases: ["anthropic/claude-3-haiku-20240307"],
    releasedAt: "2024-03-13",
    source: "https://docs.anthropic.com/en/docs/about-claude/models",
    contextSource: "https://docs.anthropic.com/en/docs/about-claude/models",
    verifiedAt: "2024-03-13",
  },
  {
    id: "anthropic:claude-3-opus-20240229",
    provider: "anthropic",
    vendorId: "claude-3-opus-20240229",
    displayName: "Claude Opus 3",
    family: "claude-3-opus-20240229",
    status: "stable",
    context: {"combinedMax":200000,"outputMax":4096},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":15,"outputPerMTokens":75},
    pricingSource: "models.dev",
    aliases: ["anthropic/claude-3-opus-20240229"],
    releasedAt: "2024-02-29",
    source: "https://docs.anthropic.com/en/docs/about-claude/models",
    contextSource: "https://docs.anthropic.com/en/docs/about-claude/models",
    verifiedAt: "2024-02-29",
  },
  {
    id: "anthropic:claude-3-sonnet-20240229",
    provider: "anthropic",
    vendorId: "claude-3-sonnet-20240229",
    displayName: "Claude Sonnet 3",
    family: "claude-3-sonnet-20240229",
    status: "stable",
    context: {"combinedMax":200000,"outputMax":4096},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":3,"outputPerMTokens":15},
    pricingSource: "models.dev",
    aliases: ["anthropic/claude-3-sonnet-20240229"],
    releasedAt: "2024-03-04",
    source: "https://docs.anthropic.com/en/docs/about-claude/models",
    contextSource: "https://docs.anthropic.com/en/docs/about-claude/models",
    verifiedAt: "2024-03-04",
  },
  {
    id: "anthropic:claude-opus-4-1-20250805",
    provider: "anthropic",
    vendorId: "claude-opus-4-1-20250805",
    displayName: "Claude Opus 4.1",
    family: "claude-opus-4-1-20250805",
    status: "stable",
    context: {"combinedMax":200000,"outputMax":32000},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":15,"outputPerMTokens":75},
    pricingSource: "models.dev",
    aliases: ["anthropic/claude-opus-4-1-20250805"],
    releasedAt: "2025-08-05",
    source: "https://docs.anthropic.com/en/docs/about-claude/models",
    contextSource: "https://docs.anthropic.com/en/docs/about-claude/models",
    verifiedAt: "2025-08-05",
  },
  {
    id: "anthropic:claude-opus-4-20250514",
    provider: "anthropic",
    vendorId: "claude-opus-4-20250514",
    displayName: "Claude Opus 4",
    family: "claude-opus-4-20250514",
    status: "stable",
    context: {"combinedMax":200000,"outputMax":32000},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":15,"outputPerMTokens":75},
    pricingSource: "models.dev",
    aliases: ["anthropic/claude-opus-4-20250514"],
    releasedAt: "2025-05-22",
    source: "https://docs.anthropic.com/en/docs/about-claude/models",
    contextSource: "https://docs.anthropic.com/en/docs/about-claude/models",
    verifiedAt: "2025-05-22",
  },
  {
    id: "anthropic:claude-sonnet-4-20250514",
    provider: "anthropic",
    vendorId: "claude-sonnet-4-20250514",
    displayName: "Claude Sonnet 4",
    family: "claude-sonnet-4-20250514",
    status: "stable",
    context: {"combinedMax":200000,"outputMax":64000},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":3,"outputPerMTokens":15},
    pricingSource: "models.dev",
    aliases: ["anthropic/claude-sonnet-4-20250514"],
    releasedAt: "2025-05-22",
    source: "https://docs.anthropic.com/en/docs/about-claude/models",
    contextSource: "https://docs.anthropic.com/en/docs/about-claude/models",
    verifiedAt: "2025-05-22",
  },
  {
    id: "deepseek:deepseek-chat",
    provider: "deepseek",
    vendorId: "deepseek-chat",
    displayName: "DeepSeek Chat",
    family: "deepseek-chat",
    status: "stable",
    context: {"combinedMax":128000,"outputMax":8192},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":0.57,"outputPerMTokens":1.68},
    pricingSource: "models.dev",
    aliases: ["deepseek/deepseek-chat"],
    releasedAt: "2024-12-26",
    source: "https://platform.deepseek.com/api-docs/pricing",
    contextSource: "https://platform.deepseek.com/api-docs/pricing",
    verifiedAt: "2025-08-21",
  },
  {
    id: "deepseek:deepseek-reasoner",
    provider: "deepseek",
    vendorId: "deepseek-reasoner",
    displayName: "DeepSeek Reasoner",
    family: "deepseek-reasoner",
    status: "stable",
    context: {"combinedMax":128000,"outputMax":128000},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":0.57,"outputPerMTokens":1.68},
    pricingSource: "models.dev",
    aliases: ["deepseek/deepseek-reasoner"],
    releasedAt: "2025-01-20",
    source: "https://platform.deepseek.com/api-docs/pricing",
    contextSource: "https://platform.deepseek.com/api-docs/pricing",
    verifiedAt: "2025-08-21",
  },
  {
    id: "google:gemini-1.5-flash",
    provider: "google",
    vendorId: "gemini-1.5-flash",
    displayName: "Gemini 1.5 Flash",
    family: "gemini-1.5-flash",
    status: "stable",
    context: {"combinedMax":1000000,"outputMax":8192},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":0.075,"outputPerMTokens":0.3},
    pricingSource: "models.dev",
    aliases: ["google/gemini-1.5-flash"],
    releasedAt: "2024-05-14",
    source: "https://ai.google.dev/gemini-api/docs/pricing",
    contextSource: "https://ai.google.dev/gemini-api/docs/pricing",
    verifiedAt: "2024-05-14",
  },
  {
    id: "google:gemini-1.5-flash-8b",
    provider: "google",
    vendorId: "gemini-1.5-flash-8b",
    displayName: "Gemini 1.5 Flash-8B",
    family: "gemini-1.5-flash-8b",
    status: "stable",
    context: {"combinedMax":1000000,"outputMax":8192},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":0.0375,"outputPerMTokens":0.15},
    pricingSource: "models.dev",
    aliases: ["google/gemini-1.5-flash-8b"],
    releasedAt: "2024-10-03",
    source: "https://ai.google.dev/gemini-api/docs/pricing",
    contextSource: "https://ai.google.dev/gemini-api/docs/pricing",
    verifiedAt: "2024-10-03",
  },
  {
    id: "google:gemini-1.5-pro",
    provider: "google",
    vendorId: "gemini-1.5-pro",
    displayName: "Gemini 1.5 Pro",
    family: "gemini-1.5-pro",
    status: "stable",
    context: {"combinedMax":1000000,"outputMax":8192},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":1.25,"outputPerMTokens":5},
    pricingSource: "models.dev",
    aliases: ["google/gemini-1.5-pro"],
    releasedAt: "2024-02-15",
    source: "https://ai.google.dev/gemini-api/docs/pricing",
    contextSource: "https://ai.google.dev/gemini-api/docs/pricing",
    verifiedAt: "2024-02-15",
  },
  {
    id: "google:gemini-2.0-flash",
    provider: "google",
    vendorId: "gemini-2.0-flash",
    displayName: "Gemini 2.0 Flash",
    family: "gemini-2.0-flash",
    status: "stable",
    context: {"combinedMax":1048576,"outputMax":8192},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":0.1,"outputPerMTokens":0.4},
    pricingSource: "models.dev",
    aliases: ["google/gemini-2.0-flash"],
    releasedAt: "2024-12-11",
    source: "https://ai.google.dev/gemini-api/docs/pricing",
    contextSource: "https://ai.google.dev/gemini-api/docs/pricing",
    verifiedAt: "2024-12-11",
  },
  {
    id: "google:gemini-2.0-flash-lite",
    provider: "google",
    vendorId: "gemini-2.0-flash-lite",
    displayName: "Gemini 2.0 Flash Lite",
    family: "gemini-2.0-flash-lite",
    status: "stable",
    context: {"combinedMax":1048576,"outputMax":8192},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":0.075,"outputPerMTokens":0.3},
    pricingSource: "models.dev",
    aliases: ["google/gemini-2.0-flash-lite"],
    releasedAt: "2024-12-11",
    source: "https://ai.google.dev/gemini-api/docs/pricing",
    contextSource: "https://ai.google.dev/gemini-api/docs/pricing",
    verifiedAt: "2024-12-11",
  },
  {
    id: "google:gemini-2.5-flash",
    provider: "google",
    vendorId: "gemini-2.5-flash",
    displayName: "Gemini 2.5 Flash",
    family: "gemini-2.5-flash",
    status: "stable",
    context: {"combinedMax":1048576,"outputMax":65536},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":0.3,"outputPerMTokens":2.5},
    pricingSource: "models.dev",
    aliases: ["google/gemini-2.5-flash"],
    releasedAt: "2025-03-20",
    source: "https://ai.google.dev/gemini-api/docs/pricing",
    contextSource: "https://ai.google.dev/gemini-api/docs/pricing",
    verifiedAt: "2025-06-05",
  },
  {
    id: "google:gemini-2.5-flash-lite-preview-06-17",
    provider: "google",
    vendorId: "gemini-2.5-flash-lite-preview-06-17",
    displayName: "Gemini 2.5 Flash Lite Preview 06-17",
    family: "gemini-2.5-flash-lite-preview-06-17",
    status: "stable",
    context: {"combinedMax":65536,"outputMax":65536},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":0.1,"outputPerMTokens":0.4},
    pricingSource: "models.dev",
    aliases: ["google/gemini-2.5-flash-lite-preview-06-17"],
    releasedAt: "2025-06-17",
    source: "https://ai.google.dev/gemini-api/docs/pricing",
    contextSource: "https://ai.google.dev/gemini-api/docs/pricing",
    verifiedAt: "2025-06-17",
  },
  {
    id: "google:gemini-2.5-flash-preview-04-17",
    provider: "google",
    vendorId: "gemini-2.5-flash-preview-04-17",
    displayName: "Gemini 2.5 Flash Preview 04-17",
    family: "gemini-2.5-flash-preview-04-17",
    status: "stable",
    context: {"combinedMax":1048576,"outputMax":65536},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":0.15,"outputPerMTokens":0.6},
    pricingSource: "models.dev",
    aliases: ["google/gemini-2.5-flash-preview-04-17"],
    releasedAt: "2025-04-17",
    source: "https://ai.google.dev/gemini-api/docs/pricing",
    contextSource: "https://ai.google.dev/gemini-api/docs/pricing",
    verifiedAt: "2025-04-17",
  },
  {
    id: "google:gemini-2.5-flash-preview-05-20",
    provider: "google",
    vendorId: "gemini-2.5-flash-preview-05-20",
    displayName: "Gemini 2.5 Flash Preview 05-20",
    family: "gemini-2.5-flash-preview-05-20",
    status: "stable",
    context: {"combinedMax":1048576,"outputMax":65536},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":0.15,"outputPerMTokens":0.6},
    pricingSource: "models.dev",
    aliases: ["google/gemini-2.5-flash-preview-05-20"],
    releasedAt: "2025-05-20",
    source: "https://ai.google.dev/gemini-api/docs/pricing",
    contextSource: "https://ai.google.dev/gemini-api/docs/pricing",
    verifiedAt: "2025-05-20",
  },
  {
    id: "google:gemini-2.5-pro",
    provider: "google",
    vendorId: "gemini-2.5-pro",
    displayName: "Gemini 2.5 Pro",
    family: "gemini-2.5-pro",
    status: "stable",
    context: {"combinedMax":1048576,"outputMax":65536},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":1.25,"outputPerMTokens":10},
    pricingSource: "models.dev",
    aliases: ["google/gemini-2.5-pro"],
    releasedAt: "2025-03-20",
    source: "https://ai.google.dev/gemini-api/docs/pricing",
    contextSource: "https://ai.google.dev/gemini-api/docs/pricing",
    verifiedAt: "2025-06-05",
  },
  {
    id: "google:gemini-2.5-pro-preview-05-06",
    provider: "google",
    vendorId: "gemini-2.5-pro-preview-05-06",
    displayName: "Gemini 2.5 Pro Preview 05-06",
    family: "gemini-2.5-pro-preview-05-06",
    status: "stable",
    context: {"combinedMax":1048576,"outputMax":65536},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":1.25,"outputPerMTokens":10},
    pricingSource: "models.dev",
    aliases: ["google/gemini-2.5-pro-preview-05-06"],
    releasedAt: "2025-05-06",
    source: "https://ai.google.dev/gemini-api/docs/pricing",
    contextSource: "https://ai.google.dev/gemini-api/docs/pricing",
    verifiedAt: "2025-05-06",
  },
  {
    id: "google:gemini-2.5-pro-preview-06-05",
    provider: "google",
    vendorId: "gemini-2.5-pro-preview-06-05",
    displayName: "Gemini 2.5 Pro Preview 06-05",
    family: "gemini-2.5-pro-preview-06-05",
    status: "stable",
    context: {"combinedMax":1048576,"outputMax":65536},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":1.25,"outputPerMTokens":10},
    pricingSource: "models.dev",
    aliases: ["google/gemini-2.5-pro-preview-06-05"],
    releasedAt: "2025-06-05",
    source: "https://ai.google.dev/gemini-api/docs/pricing",
    contextSource: "https://ai.google.dev/gemini-api/docs/pricing",
    verifiedAt: "2025-06-05",
  },
  {
    id: "mistral:codestral-latest",
    provider: "mistral",
    vendorId: "codestral-latest",
    displayName: "Codestral",
    family: "codestral-latest",
    status: "stable",
    context: {"combinedMax":256000,"outputMax":4096},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":0.3,"outputPerMTokens":0.9},
    pricingSource: "models.dev",
    aliases: ["mistral/codestral-latest"],
    releasedAt: "2024-05-29",
    source: "https://docs.mistral.ai/getting-started/models/",
    contextSource: "https://docs.mistral.ai/getting-started/models/",
    verifiedAt: "2025-01-04",
  },
  {
    id: "mistral:devstral-medium-2507",
    provider: "mistral",
    vendorId: "devstral-medium-2507",
    displayName: "Devstral Medium",
    family: "devstral-medium-2507",
    status: "stable",
    context: {"combinedMax":128000,"outputMax":128000},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":0.4,"outputPerMTokens":2},
    pricingSource: "models.dev",
    aliases: ["mistral/devstral-medium-2507"],
    releasedAt: "2025-07-10",
    source: "https://docs.mistral.ai/getting-started/models/",
    contextSource: "https://docs.mistral.ai/getting-started/models/",
    verifiedAt: "2025-07-10",
  },
  {
    id: "mistral:devstral-small-2505",
    provider: "mistral",
    vendorId: "devstral-small-2505",
    displayName: "Devstral Small 2505",
    family: "devstral-small-2505",
    status: "stable",
    context: {"combinedMax":128000,"outputMax":128000},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":0.1,"outputPerMTokens":0.3},
    pricingSource: "models.dev",
    aliases: ["mistral/devstral-small-2505"],
    releasedAt: "2025-05-07",
    source: "https://docs.mistral.ai/getting-started/models/",
    contextSource: "https://docs.mistral.ai/getting-started/models/",
    verifiedAt: "2025-05-07",
  },
  {
    id: "mistral:devstral-small-2507",
    provider: "mistral",
    vendorId: "devstral-small-2507",
    displayName: "Devstral Small",
    family: "devstral-small-2507",
    status: "stable",
    context: {"combinedMax":128000,"outputMax":128000},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":0.1,"outputPerMTokens":0.3},
    pricingSource: "models.dev",
    aliases: ["mistral/devstral-small-2507"],
    releasedAt: "2025-07-10",
    source: "https://docs.mistral.ai/getting-started/models/",
    contextSource: "https://docs.mistral.ai/getting-started/models/",
    verifiedAt: "2025-07-10",
  },
  {
    id: "mistral:magistral-medium-latest",
    provider: "mistral",
    vendorId: "magistral-medium-latest",
    displayName: "Magistral Medium",
    family: "magistral-medium-latest",
    status: "stable",
    context: {"combinedMax":128000,"outputMax":16384},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":2,"outputPerMTokens":5},
    pricingSource: "models.dev",
    aliases: ["mistral/magistral-medium-latest"],
    releasedAt: "2025-03-17",
    source: "https://docs.mistral.ai/getting-started/models/",
    contextSource: "https://docs.mistral.ai/getting-started/models/",
    verifiedAt: "2025-03-20",
  },
  {
    id: "mistral:magistral-small",
    provider: "mistral",
    vendorId: "magistral-small",
    displayName: "Magistral Small",
    family: "magistral-small",
    status: "stable",
    context: {"combinedMax":128000,"outputMax":128000},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":0.5,"outputPerMTokens":1.5},
    pricingSource: "models.dev",
    aliases: ["mistral/magistral-small"],
    releasedAt: "2025-03-17",
    source: "https://docs.mistral.ai/getting-started/models/",
    contextSource: "https://docs.mistral.ai/getting-started/models/",
    verifiedAt: "2025-03-17",
  },
  {
    id: "mistral:ministral-3b-latest",
    provider: "mistral",
    vendorId: "ministral-3b-latest",
    displayName: "Ministral 3B",
    family: "ministral-3b-latest",
    status: "stable",
    context: {"combinedMax":128000,"outputMax":128000},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":0.04,"outputPerMTokens":0.04},
    pricingSource: "models.dev",
    aliases: ["mistral/ministral-3b-latest"],
    releasedAt: "2024-10-01",
    source: "https://docs.mistral.ai/getting-started/models/",
    contextSource: "https://docs.mistral.ai/getting-started/models/",
    verifiedAt: "2024-10-04",
  },
  {
    id: "mistral:ministral-8b-latest",
    provider: "mistral",
    vendorId: "ministral-8b-latest",
    displayName: "Ministral 8B",
    family: "ministral-8b-latest",
    status: "stable",
    context: {"combinedMax":128000,"outputMax":128000},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":0.1,"outputPerMTokens":0.1},
    pricingSource: "models.dev",
    aliases: ["mistral/ministral-8b-latest"],
    releasedAt: "2024-10-01",
    source: "https://docs.mistral.ai/getting-started/models/",
    contextSource: "https://docs.mistral.ai/getting-started/models/",
    verifiedAt: "2024-10-04",
  },
  {
    id: "mistral:mistral-large-latest",
    provider: "mistral",
    vendorId: "mistral-large-latest",
    displayName: "Mistral Large",
    family: "mistral-large-latest",
    status: "stable",
    context: {"combinedMax":131072,"outputMax":16384},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":2,"outputPerMTokens":6},
    pricingSource: "models.dev",
    aliases: ["mistral/mistral-large-latest"],
    releasedAt: "2024-11-01",
    source: "https://docs.mistral.ai/getting-started/models/",
    contextSource: "https://docs.mistral.ai/getting-started/models/",
    verifiedAt: "2024-11-04",
  },
  {
    id: "mistral:mistral-medium-2505",
    provider: "mistral",
    vendorId: "mistral-medium-2505",
    displayName: "Mistral Medium 3",
    family: "mistral-medium-2505",
    status: "stable",
    context: {"combinedMax":131072,"outputMax":131072},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":0.4,"outputPerMTokens":2},
    pricingSource: "models.dev",
    aliases: ["mistral/mistral-medium-2505"],
    releasedAt: "2025-05-07",
    source: "https://docs.mistral.ai/getting-started/models/",
    contextSource: "https://docs.mistral.ai/getting-started/models/",
    verifiedAt: "2025-05-07",
  },
  {
    id: "mistral:mistral-medium-2508",
    provider: "mistral",
    vendorId: "mistral-medium-2508",
    displayName: "Mistral Medium 3.1",
    family: "mistral-medium-2508",
    status: "stable",
    context: {"combinedMax":262144,"outputMax":262144},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":0.4,"outputPerMTokens":2},
    pricingSource: "models.dev",
    aliases: ["mistral/mistral-medium-2508"],
    releasedAt: "2025-08-12",
    source: "https://docs.mistral.ai/getting-started/models/",
    contextSource: "https://docs.mistral.ai/getting-started/models/",
    verifiedAt: "2025-08-12",
  },
  {
    id: "mistral:mistral-medium-latest",
    provider: "mistral",
    vendorId: "mistral-medium-latest",
    displayName: "Mistral Medium",
    family: "mistral-medium-latest",
    status: "stable",
    context: {"combinedMax":128000,"outputMax":16384},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":0.4,"outputPerMTokens":2},
    pricingSource: "models.dev",
    aliases: ["mistral/mistral-medium-latest"],
    releasedAt: "2025-05-07",
    source: "https://docs.mistral.ai/getting-started/models/",
    contextSource: "https://docs.mistral.ai/getting-started/models/",
    verifiedAt: "2025-05-10",
  },
  {
    id: "mistral:mistral-nemo",
    provider: "mistral",
    vendorId: "mistral-nemo",
    displayName: "Mistral Nemo",
    family: "mistral-nemo",
    status: "stable",
    context: {"combinedMax":128000,"outputMax":128000},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":0.15,"outputPerMTokens":0.15},
    pricingSource: "models.dev",
    aliases: ["mistral/mistral-nemo"],
    releasedAt: "2024-07-01",
    source: "https://docs.mistral.ai/getting-started/models/",
    contextSource: "https://docs.mistral.ai/getting-started/models/",
    verifiedAt: "2024-07-01",
  },
  {
    id: "mistral:mistral-small-latest",
    provider: "mistral",
    vendorId: "mistral-small-latest",
    displayName: "Mistral Small",
    family: "mistral-small-latest",
    status: "stable",
    context: {"combinedMax":128000,"outputMax":16384},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":0.1,"outputPerMTokens":0.3},
    pricingSource: "models.dev",
    aliases: ["mistral/mistral-small-latest"],
    releasedAt: "2024-09-01",
    source: "https://docs.mistral.ai/getting-started/models/",
    contextSource: "https://docs.mistral.ai/getting-started/models/",
    verifiedAt: "2024-09-04",
  },
  {
    id: "mistral:open-mistral-7b",
    provider: "mistral",
    vendorId: "open-mistral-7b",
    displayName: "Mistral 7B",
    family: "open-mistral-7b",
    status: "stable",
    context: {"combinedMax":8000,"outputMax":8000},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":0.25,"outputPerMTokens":0.25},
    pricingSource: "models.dev",
    aliases: ["mistral/open-mistral-7b"],
    releasedAt: "2023-09-27",
    source: "https://docs.mistral.ai/getting-started/models/",
    contextSource: "https://docs.mistral.ai/getting-started/models/",
    verifiedAt: "2023-09-27",
  },
  {
    id: "mistral:open-mixtral-8x22b",
    provider: "mistral",
    vendorId: "open-mixtral-8x22b",
    displayName: "Mixtral 8x22B",
    family: "open-mixtral-8x22b",
    status: "stable",
    context: {"combinedMax":64000,"outputMax":64000},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":2,"outputPerMTokens":6},
    pricingSource: "models.dev",
    aliases: ["mistral/open-mixtral-8x22b"],
    releasedAt: "2024-04-17",
    source: "https://docs.mistral.ai/getting-started/models/",
    contextSource: "https://docs.mistral.ai/getting-started/models/",
    verifiedAt: "2024-04-17",
  },
  {
    id: "mistral:open-mixtral-8x7b",
    provider: "mistral",
    vendorId: "open-mixtral-8x7b",
    displayName: "Mixtral 8x7B",
    family: "open-mixtral-8x7b",
    status: "stable",
    context: {"combinedMax":32000,"outputMax":32000},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":0.7,"outputPerMTokens":0.7},
    pricingSource: "models.dev",
    aliases: ["mistral/open-mixtral-8x7b"],
    releasedAt: "2023-12-11",
    source: "https://docs.mistral.ai/getting-started/models/",
    contextSource: "https://docs.mistral.ai/getting-started/models/",
    verifiedAt: "2023-12-11",
  },
  {
    id: "mistral:pixtral-12b",
    provider: "mistral",
    vendorId: "pixtral-12b",
    displayName: "Pixtral 12B",
    family: "pixtral-12b",
    status: "stable",
    context: {"combinedMax":128000,"outputMax":128000},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":0.15,"outputPerMTokens":0.15},
    pricingSource: "models.dev",
    aliases: ["mistral/pixtral-12b"],
    releasedAt: "2024-09-01",
    source: "https://docs.mistral.ai/getting-started/models/",
    contextSource: "https://docs.mistral.ai/getting-started/models/",
    verifiedAt: "2024-09-01",
  },
  {
    id: "mistral:pixtral-large-latest",
    provider: "mistral",
    vendorId: "pixtral-large-latest",
    displayName: "Pixtral Large",
    family: "pixtral-large-latest",
    status: "stable",
    context: {"combinedMax":128000,"outputMax":128000},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":2,"outputPerMTokens":6},
    pricingSource: "models.dev",
    aliases: ["mistral/pixtral-large-latest"],
    releasedAt: "2024-11-01",
    source: "https://docs.mistral.ai/getting-started/models/",
    contextSource: "https://docs.mistral.ai/getting-started/models/",
    verifiedAt: "2024-11-04",
  },
  {
    id: "moonshotai:kimi-k2-0711-preview",
    provider: "moonshotai",
    vendorId: "kimi-k2-0711-preview",
    displayName: "Kimi K2 0711",
    family: "kimi-k2-0711-preview",
    status: "stable",
    context: {"combinedMax":131072,"outputMax":16384},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":0.6,"outputPerMTokens":2.5},
    pricingSource: "models.dev",
    aliases: ["moonshotai/kimi-k2-0711-preview"],
    releasedAt: "2025-07-14",
    source: "https://platform.moonshot.ai/docs/api/chat",
    contextSource: "https://platform.moonshot.ai/docs/api/chat",
    verifiedAt: "2025-07-14",
  },
  {
    id: "moonshotai:kimi-k2-0905-preview",
    provider: "moonshotai",
    vendorId: "kimi-k2-0905-preview",
    displayName: "Kimi K2 0905",
    family: "kimi-k2-0905-preview",
    status: "stable",
    context: {"combinedMax":262144,"outputMax":262144},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":0.6,"outputPerMTokens":2.5},
    pricingSource: "models.dev",
    aliases: ["moonshotai/kimi-k2-0905-preview"],
    releasedAt: "2025-09-05",
    source: "https://platform.moonshot.ai/docs/api/chat",
    contextSource: "https://platform.moonshot.ai/docs/api/chat",
    verifiedAt: "2025-09-05",
  },
  {
    id: "moonshotai:kimi-k2-turbo-preview",
    provider: "moonshotai",
    vendorId: "kimi-k2-turbo-preview",
    displayName: "Kimi K2 Turbo",
    family: "kimi-k2-turbo-preview",
    status: "stable",
    context: {"combinedMax":131072,"outputMax":16384},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":2.4,"outputPerMTokens":10},
    pricingSource: "models.dev",
    aliases: ["moonshotai/kimi-k2-turbo-preview"],
    releasedAt: "2025-07-14",
    source: "https://platform.moonshot.ai/docs/api/chat",
    contextSource: "https://platform.moonshot.ai/docs/api/chat",
    verifiedAt: "2025-07-14",
  },
  {
    id: "openai:codex-mini-latest",
    provider: "openai",
    vendorId: "codex-mini-latest",
    displayName: "Codex Mini",
    family: "codex-mini-latest",
    status: "stable",
    context: {"combinedMax":200000,"outputMax":100000},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":1.5,"outputPerMTokens":6},
    pricingSource: "models.dev",
    aliases: ["openai/codex-mini-latest"],
    releasedAt: "2025-05-16",
    source: "https://platform.openai.com/docs/models",
    contextSource: "https://platform.openai.com/docs/models",
    verifiedAt: "2025-05-16",
  },
  {
    id: "openai:gpt-3.5-turbo",
    provider: "openai",
    vendorId: "gpt-3.5-turbo",
    displayName: "GPT-3.5-turbo",
    family: "gpt-3.5-turbo",
    status: "stable",
    context: {"combinedMax":16385,"outputMax":4096},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":0.5,"outputPerMTokens":1.5},
    pricingSource: "models.dev",
    aliases: ["openai/gpt-3.5-turbo"],
    releasedAt: "2023-03-01",
    source: "https://platform.openai.com/docs/models",
    contextSource: "https://platform.openai.com/docs/models",
    verifiedAt: "2023-11-06",
  },
  {
    id: "openai:gpt-4",
    provider: "openai",
    vendorId: "gpt-4",
    displayName: "GPT-4",
    family: "gpt-4",
    status: "stable",
    context: {"combinedMax":8192,"outputMax":8192},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":30,"outputPerMTokens":60},
    pricingSource: "models.dev",
    aliases: ["openai/gpt-4"],
    releasedAt: "2023-11-06",
    source: "https://platform.openai.com/docs/models",
    contextSource: "https://platform.openai.com/docs/models",
    verifiedAt: "2024-04-09",
  },
  {
    id: "openai:gpt-4-turbo",
    provider: "openai",
    vendorId: "gpt-4-turbo",
    displayName: "GPT-4 Turbo",
    family: "gpt-4-turbo",
    status: "stable",
    context: {"combinedMax":128000,"outputMax":4096},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":10,"outputPerMTokens":30},
    pricingSource: "models.dev",
    aliases: ["openai/gpt-4-turbo"],
    releasedAt: "2023-11-06",
    source: "https://platform.openai.com/docs/models",
    contextSource: "https://platform.openai.com/docs/models",
    verifiedAt: "2024-04-09",
  },
  {
    id: "openai:gpt-4.1",
    provider: "openai",
    vendorId: "gpt-4.1",
    displayName: "GPT-4.1",
    family: "gpt-4.1",
    status: "stable",
    context: {"combinedMax":1047576,"outputMax":32768},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":2,"outputPerMTokens":8},
    pricingSource: "models.dev",
    aliases: ["openai/gpt-4.1"],
    releasedAt: "2025-04-14",
    source: "https://platform.openai.com/docs/models",
    contextSource: "https://platform.openai.com/docs/models",
    verifiedAt: "2025-04-14",
  },
  {
    id: "openai:gpt-4.1-mini",
    provider: "openai",
    vendorId: "gpt-4.1-mini",
    displayName: "GPT-4.1 mini",
    family: "gpt-4.1-mini",
    status: "stable",
    context: {"combinedMax":1047576,"outputMax":32768},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":0.4,"outputPerMTokens":1.6},
    pricingSource: "models.dev",
    aliases: ["openai/gpt-4.1-mini"],
    releasedAt: "2025-04-14",
    source: "https://platform.openai.com/docs/models",
    contextSource: "https://platform.openai.com/docs/models",
    verifiedAt: "2025-04-14",
  },
  {
    id: "openai:gpt-4.1-nano",
    provider: "openai",
    vendorId: "gpt-4.1-nano",
    displayName: "GPT-4.1 nano",
    family: "gpt-4.1-nano",
    status: "stable",
    context: {"combinedMax":1047576,"outputMax":32768},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":0.1,"outputPerMTokens":0.4},
    pricingSource: "models.dev",
    aliases: ["openai/gpt-4.1-nano"],
    releasedAt: "2025-04-14",
    source: "https://platform.openai.com/docs/models",
    contextSource: "https://platform.openai.com/docs/models",
    verifiedAt: "2025-04-14",
  },
  {
    id: "openai:gpt-4o",
    provider: "openai",
    vendorId: "gpt-4o",
    displayName: "GPT-4o",
    family: "gpt-4o",
    status: "stable",
    context: {"combinedMax":128000,"outputMax":16384},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":2.5,"outputPerMTokens":10},
    pricingSource: "models.dev",
    aliases: ["openai/gpt-4o"],
    releasedAt: "2024-05-13",
    source: "https://platform.openai.com/docs/models",
    contextSource: "https://platform.openai.com/docs/models",
    verifiedAt: "2024-05-13",
  },
  {
    id: "openai:gpt-4o-mini",
    provider: "openai",
    vendorId: "gpt-4o-mini",
    displayName: "GPT-4o mini",
    family: "gpt-4o-mini",
    status: "stable",
    context: {"combinedMax":128000,"outputMax":16384},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":0.15,"outputPerMTokens":0.6},
    pricingSource: "models.dev",
    aliases: ["openai/gpt-4o-mini"],
    releasedAt: "2024-07-18",
    source: "https://platform.openai.com/docs/models",
    contextSource: "https://platform.openai.com/docs/models",
    verifiedAt: "2024-07-18",
  },
  {
    id: "openai:gpt-5",
    provider: "openai",
    vendorId: "gpt-5",
    displayName: "GPT-5",
    family: "gpt-5",
    status: "stable",
    context: {"combinedMax":400000,"outputMax":128000},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":1.25,"outputPerMTokens":10},
    pricingSource: "models.dev",
    aliases: ["openai/gpt-5"],
    releasedAt: "2025-08-07",
    source: "https://platform.openai.com/docs/models",
    contextSource: "https://platform.openai.com/docs/models",
    verifiedAt: "2025-08-07",
  },
  {
    id: "openai:gpt-5-chat-latest",
    provider: "openai",
    vendorId: "gpt-5-chat-latest",
    displayName: "GPT-5 Chat (latest)",
    family: "gpt-5-chat-latest",
    status: "stable",
    context: {"combinedMax":400000,"outputMax":128000},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":1.25,"outputPerMTokens":10},
    pricingSource: "models.dev",
    aliases: ["openai/gpt-5-chat-latest"],
    releasedAt: "2025-08-07",
    source: "https://platform.openai.com/docs/models",
    contextSource: "https://platform.openai.com/docs/models",
    verifiedAt: "2025-08-07",
  },
  {
    id: "openai:gpt-5-mini",
    provider: "openai",
    vendorId: "gpt-5-mini",
    displayName: "GPT-5 Mini",
    family: "gpt-5-mini",
    status: "stable",
    context: {"combinedMax":400000,"outputMax":128000},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":0.25,"outputPerMTokens":2},
    pricingSource: "models.dev",
    aliases: ["openai/gpt-5-mini"],
    releasedAt: "2025-08-07",
    source: "https://platform.openai.com/docs/models",
    contextSource: "https://platform.openai.com/docs/models",
    verifiedAt: "2025-08-07",
  },
  {
    id: "openai:gpt-5-nano",
    provider: "openai",
    vendorId: "gpt-5-nano",
    displayName: "GPT-5 Nano",
    family: "gpt-5-nano",
    status: "stable",
    context: {"combinedMax":400000,"outputMax":128000},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":0.05,"outputPerMTokens":0.4},
    pricingSource: "models.dev",
    aliases: ["openai/gpt-5-nano"],
    releasedAt: "2025-08-07",
    source: "https://platform.openai.com/docs/models",
    contextSource: "https://platform.openai.com/docs/models",
    verifiedAt: "2025-08-07",
  },
  {
    id: "openai:o1",
    provider: "openai",
    vendorId: "o1",
    displayName: "o1",
    family: "o1",
    status: "stable",
    context: {"combinedMax":200000,"outputMax":100000},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":15,"outputPerMTokens":60},
    pricingSource: "models.dev",
    aliases: ["openai/o1"],
    releasedAt: "2024-12-05",
    source: "https://platform.openai.com/docs/models",
    contextSource: "https://platform.openai.com/docs/models",
    verifiedAt: "2024-12-05",
  },
  {
    id: "openai:o1-mini",
    provider: "openai",
    vendorId: "o1-mini",
    displayName: "o1-mini",
    family: "o1-mini",
    status: "stable",
    context: {"combinedMax":128000,"outputMax":65536},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":1.1,"outputPerMTokens":4.4},
    pricingSource: "models.dev",
    aliases: ["openai/o1-mini"],
    releasedAt: "2024-09-12",
    source: "https://platform.openai.com/docs/models",
    contextSource: "https://platform.openai.com/docs/models",
    verifiedAt: "2024-09-12",
  },
  {
    id: "openai:o1-preview",
    provider: "openai",
    vendorId: "o1-preview",
    displayName: "o1-preview",
    family: "o1-preview",
    status: "stable",
    context: {"combinedMax":128000,"outputMax":32768},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":15,"outputPerMTokens":60},
    pricingSource: "models.dev",
    aliases: ["openai/o1-preview"],
    releasedAt: "2024-09-12",
    source: "https://platform.openai.com/docs/models",
    contextSource: "https://platform.openai.com/docs/models",
    verifiedAt: "2024-09-12",
  },
  {
    id: "openai:o1-pro",
    provider: "openai",
    vendorId: "o1-pro",
    displayName: "o1-pro",
    family: "o1-pro",
    status: "stable",
    context: {"combinedMax":200000,"outputMax":100000},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":150,"outputPerMTokens":600},
    pricingSource: "models.dev",
    aliases: ["openai/o1-pro"],
    releasedAt: "2025-03-19",
    source: "https://platform.openai.com/docs/models",
    contextSource: "https://platform.openai.com/docs/models",
    verifiedAt: "2025-03-19",
  },
  {
    id: "openai:o3",
    provider: "openai",
    vendorId: "o3",
    displayName: "o3",
    family: "o3",
    status: "stable",
    context: {"combinedMax":200000,"outputMax":100000},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":2,"outputPerMTokens":8},
    pricingSource: "models.dev",
    aliases: ["openai/o3"],
    releasedAt: "2025-04-16",
    source: "https://platform.openai.com/docs/models",
    contextSource: "https://platform.openai.com/docs/models",
    verifiedAt: "2025-04-16",
  },
  {
    id: "openai:o3-deep-research",
    provider: "openai",
    vendorId: "o3-deep-research",
    displayName: "o3-deep-research",
    family: "o3-deep-research",
    status: "stable",
    context: {"combinedMax":200000,"outputMax":100000},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":10,"outputPerMTokens":40},
    pricingSource: "models.dev",
    aliases: ["openai/o3-deep-research"],
    releasedAt: "2024-06-26",
    source: "https://platform.openai.com/docs/models",
    contextSource: "https://platform.openai.com/docs/models",
    verifiedAt: "2024-06-26",
  },
  {
    id: "openai:o3-mini",
    provider: "openai",
    vendorId: "o3-mini",
    displayName: "o3-mini",
    family: "o3-mini",
    status: "stable",
    context: {"combinedMax":200000,"outputMax":100000},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":1.1,"outputPerMTokens":4.4},
    pricingSource: "models.dev",
    aliases: ["openai/o3-mini"],
    releasedAt: "2024-12-20",
    source: "https://platform.openai.com/docs/models",
    contextSource: "https://platform.openai.com/docs/models",
    verifiedAt: "2025-01-29",
  },
  {
    id: "openai:o3-pro",
    provider: "openai",
    vendorId: "o3-pro",
    displayName: "o3-pro",
    family: "o3-pro",
    status: "stable",
    context: {"combinedMax":200000,"outputMax":100000},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":20,"outputPerMTokens":80},
    pricingSource: "models.dev",
    aliases: ["openai/o3-pro"],
    releasedAt: "2025-06-10",
    source: "https://platform.openai.com/docs/models",
    contextSource: "https://platform.openai.com/docs/models",
    verifiedAt: "2025-06-10",
  },
  {
    id: "openai:o4-mini",
    provider: "openai",
    vendorId: "o4-mini",
    displayName: "o4-mini",
    family: "o4-mini",
    status: "stable",
    context: {"combinedMax":200000,"outputMax":100000},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":1.1,"outputPerMTokens":4.4},
    pricingSource: "models.dev",
    aliases: ["openai/o4-mini"],
    releasedAt: "2025-04-16",
    source: "https://platform.openai.com/docs/models",
    contextSource: "https://platform.openai.com/docs/models",
    verifiedAt: "2025-04-16",
  },
  {
    id: "openai:o4-mini-deep-research",
    provider: "openai",
    vendorId: "o4-mini-deep-research",
    displayName: "o4-mini-deep-research",
    family: "o4-mini-deep-research",
    status: "stable",
    context: {"combinedMax":200000,"outputMax":100000},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":2,"outputPerMTokens":8},
    pricingSource: "models.dev",
    aliases: ["openai/o4-mini-deep-research"],
    releasedAt: "2024-06-26",
    source: "https://platform.openai.com/docs/models",
    contextSource: "https://platform.openai.com/docs/models",
    verifiedAt: "2024-06-26",
  },
  {
    id: "xai:grok-2",
    provider: "xai",
    vendorId: "grok-2",
    displayName: "Grok 2",
    family: "grok-2",
    status: "stable",
    context: {"combinedMax":131072,"outputMax":8192},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":2,"outputPerMTokens":10},
    pricingSource: "models.dev",
    aliases: ["xai/grok-2"],
    releasedAt: "2024-08-20",
    source: "https://docs.x.ai/docs/models",
    contextSource: "https://docs.x.ai/docs/models",
    verifiedAt: "2024-08-20",
  },
  {
    id: "xai:grok-2-1212",
    provider: "xai",
    vendorId: "grok-2-1212",
    displayName: "Grok 2 (1212)",
    family: "grok-2-1212",
    status: "stable",
    context: {"combinedMax":131072,"outputMax":8192},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":2,"outputPerMTokens":10},
    pricingSource: "models.dev",
    aliases: ["xai/grok-2-1212"],
    releasedAt: "2024-12-12",
    source: "https://docs.x.ai/docs/models",
    contextSource: "https://docs.x.ai/docs/models",
    verifiedAt: "2024-12-12",
  },
  {
    id: "xai:grok-2-latest",
    provider: "xai",
    vendorId: "grok-2-latest",
    displayName: "Grok 2 Latest",
    family: "grok-2-latest",
    status: "stable",
    context: {"combinedMax":131072,"outputMax":8192},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":2,"outputPerMTokens":10},
    pricingSource: "models.dev",
    aliases: ["xai/grok-2-latest"],
    releasedAt: "2024-08-20",
    source: "https://docs.x.ai/docs/models",
    contextSource: "https://docs.x.ai/docs/models",
    verifiedAt: "2024-12-12",
  },
  {
    id: "xai:grok-2-vision",
    provider: "xai",
    vendorId: "grok-2-vision",
    displayName: "Grok 2 Vision",
    family: "grok-2-vision",
    status: "stable",
    context: {"combinedMax":8192,"outputMax":4096},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":2,"outputPerMTokens":10},
    pricingSource: "models.dev",
    aliases: ["xai/grok-2-vision"],
    releasedAt: "2024-08-20",
    source: "https://docs.x.ai/docs/models",
    contextSource: "https://docs.x.ai/docs/models",
    verifiedAt: "2024-08-20",
  },
  {
    id: "xai:grok-2-vision-1212",
    provider: "xai",
    vendorId: "grok-2-vision-1212",
    displayName: "Grok 2 Vision (1212)",
    family: "grok-2-vision-1212",
    status: "stable",
    context: {"combinedMax":8192,"outputMax":4096},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":2,"outputPerMTokens":10},
    pricingSource: "models.dev",
    aliases: ["xai/grok-2-vision-1212"],
    releasedAt: "2024-08-20",
    source: "https://docs.x.ai/docs/models",
    contextSource: "https://docs.x.ai/docs/models",
    verifiedAt: "2024-12-12",
  },
  {
    id: "xai:grok-2-vision-latest",
    provider: "xai",
    vendorId: "grok-2-vision-latest",
    displayName: "Grok 2 Vision Latest",
    family: "grok-2-vision-latest",
    status: "stable",
    context: {"combinedMax":8192,"outputMax":4096},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":2,"outputPerMTokens":10},
    pricingSource: "models.dev",
    aliases: ["xai/grok-2-vision-latest"],
    releasedAt: "2024-08-20",
    source: "https://docs.x.ai/docs/models",
    contextSource: "https://docs.x.ai/docs/models",
    verifiedAt: "2024-12-12",
  },
  {
    id: "xai:grok-3",
    provider: "xai",
    vendorId: "grok-3",
    displayName: "Grok 3",
    family: "grok-3",
    status: "stable",
    context: {"combinedMax":131072,"outputMax":8192},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":3,"outputPerMTokens":15},
    pricingSource: "models.dev",
    aliases: ["xai/grok-3"],
    releasedAt: "2025-02-17",
    source: "https://docs.x.ai/docs/models",
    contextSource: "https://docs.x.ai/docs/models",
    verifiedAt: "2025-02-17",
  },
  {
    id: "xai:grok-3-fast",
    provider: "xai",
    vendorId: "grok-3-fast",
    displayName: "Grok 3 Fast",
    family: "grok-3-fast",
    status: "stable",
    context: {"combinedMax":131072,"outputMax":8192},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":5,"outputPerMTokens":25},
    pricingSource: "models.dev",
    aliases: ["xai/grok-3-fast"],
    releasedAt: "2025-02-17",
    source: "https://docs.x.ai/docs/models",
    contextSource: "https://docs.x.ai/docs/models",
    verifiedAt: "2025-02-17",
  },
  {
    id: "xai:grok-3-fast-latest",
    provider: "xai",
    vendorId: "grok-3-fast-latest",
    displayName: "Grok 3 Fast Latest",
    family: "grok-3-fast-latest",
    status: "stable",
    context: {"combinedMax":131072,"outputMax":8192},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":5,"outputPerMTokens":25},
    pricingSource: "models.dev",
    aliases: ["xai/grok-3-fast-latest"],
    releasedAt: "2025-02-17",
    source: "https://docs.x.ai/docs/models",
    contextSource: "https://docs.x.ai/docs/models",
    verifiedAt: "2025-02-17",
  },
  {
    id: "xai:grok-3-latest",
    provider: "xai",
    vendorId: "grok-3-latest",
    displayName: "Grok 3 Latest",
    family: "grok-3-latest",
    status: "stable",
    context: {"combinedMax":131072,"outputMax":8192},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":3,"outputPerMTokens":15},
    pricingSource: "models.dev",
    aliases: ["xai/grok-3-latest"],
    releasedAt: "2025-02-17",
    source: "https://docs.x.ai/docs/models",
    contextSource: "https://docs.x.ai/docs/models",
    verifiedAt: "2025-02-17",
  },
  {
    id: "xai:grok-3-mini",
    provider: "xai",
    vendorId: "grok-3-mini",
    displayName: "Grok 3 Mini",
    family: "grok-3-mini",
    status: "stable",
    context: {"combinedMax":131072,"outputMax":8192},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":0.3,"outputPerMTokens":0.5},
    pricingSource: "models.dev",
    aliases: ["xai/grok-3-mini"],
    releasedAt: "2025-02-17",
    source: "https://docs.x.ai/docs/models",
    contextSource: "https://docs.x.ai/docs/models",
    verifiedAt: "2025-02-17",
  },
  {
    id: "xai:grok-3-mini-fast",
    provider: "xai",
    vendorId: "grok-3-mini-fast",
    displayName: "Grok 3 Mini Fast",
    family: "grok-3-mini-fast",
    status: "stable",
    context: {"combinedMax":131072,"outputMax":8192},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":0.6,"outputPerMTokens":4},
    pricingSource: "models.dev",
    aliases: ["xai/grok-3-mini-fast"],
    releasedAt: "2025-02-17",
    source: "https://docs.x.ai/docs/models",
    contextSource: "https://docs.x.ai/docs/models",
    verifiedAt: "2025-02-17",
  },
  {
    id: "xai:grok-3-mini-fast-latest",
    provider: "xai",
    vendorId: "grok-3-mini-fast-latest",
    displayName: "Grok 3 Mini Fast Latest",
    family: "grok-3-mini-fast-latest",
    status: "stable",
    context: {"combinedMax":131072,"outputMax":8192},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":0.6,"outputPerMTokens":4},
    pricingSource: "models.dev",
    aliases: ["xai/grok-3-mini-fast-latest"],
    releasedAt: "2025-02-17",
    source: "https://docs.x.ai/docs/models",
    contextSource: "https://docs.x.ai/docs/models",
    verifiedAt: "2025-02-17",
  },
  {
    id: "xai:grok-3-mini-latest",
    provider: "xai",
    vendorId: "grok-3-mini-latest",
    displayName: "Grok 3 Mini Latest",
    family: "grok-3-mini-latest",
    status: "stable",
    context: {"combinedMax":131072,"outputMax":8192},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":0.3,"outputPerMTokens":0.5},
    pricingSource: "models.dev",
    aliases: ["xai/grok-3-mini-latest"],
    releasedAt: "2025-02-17",
    source: "https://docs.x.ai/docs/models",
    contextSource: "https://docs.x.ai/docs/models",
    verifiedAt: "2025-02-17",
  },
  {
    id: "xai:grok-4",
    provider: "xai",
    vendorId: "grok-4",
    displayName: "Grok 4",
    family: "grok-4",
    status: "stable",
    context: {"combinedMax":256000,"outputMax":64000},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":3,"outputPerMTokens":15},
    pricingSource: "models.dev",
    aliases: ["xai/grok-4"],
    releasedAt: "2025-07-09",
    source: "https://docs.x.ai/docs/models",
    contextSource: "https://docs.x.ai/docs/models",
    verifiedAt: "2025-07-09",
  },
  {
    id: "xai:grok-beta",
    provider: "xai",
    vendorId: "grok-beta",
    displayName: "Grok Beta",
    family: "grok-beta",
    status: "stable",
    context: {"combinedMax":131072,"outputMax":4096},
    modalities: {"textIn":true,"textOut":true},
    pricing: {"inputPerMTokens":5,"outputPerMTokens":15},
    pricingSource: "models.dev",
    aliases: ["xai/grok-beta"],
    releasedAt: "2024-11-01",
    source: "https://docs.x.ai/docs/models",
    contextSource: "https://docs.x.ai/docs/models",
    verifiedAt: "2024-11-01",
  },
  {
    id: "xai:grok-vision-beta",
    provider: "xai",
    vendorId: "grok-vision-beta",
    displayName: "Grok Vision Beta",
    family: "grok-vision-beta",
    status: "stable",
    context: {"combinedMax":8192,"outputMax":4096},
    modalities: {"textIn":true,"textOut":true,"imageIn":true},
    pricing: {"inputPerMTokens":5,"outputPerMTokens":15},
    pricingSource: "models.dev",
    aliases: ["xai/grok-vision-beta"],
    releasedAt: "2024-11-01",
    source: "https://docs.x.ai/docs/models",
    contextSource: "https://docs.x.ai/docs/models",
    verifiedAt: "2024-11-01",
  }
] as const satisfies readonly Model[];

