import type { Model } from '../types.js';

/**
 * OpenAI models aligned with Vercel AI Gateway directory:
 * https://vercel.com/ai-gateway/models
 * Context windows are combined unless noted. Pricing reflects the page values per 1M tokens.
 */
export const openAIModels = [
  {
    id: 'openai:gpt-5',
    provider: 'openai',
    vendorId: 'gpt-5',
    displayName: 'GPT-5',
    family: 'gpt-5',
    status: 'stable',
    context: { combinedMax: 400_000 },
    modalities: { textIn: true, textOut: true },
    source: 'https://vercel.com/ai-gateway/models/gpt-5',
    pricing: { inputPerMTokens: 1.25, outputPerMTokens: 10.0 },
    aliases: ['gpt5', 'openai/gpt-5'],
  },
  {
    id: 'openai:gpt-5-mini',
    provider: 'openai',
    vendorId: 'gpt-5-mini',
    displayName: 'GPT-5 mini',
    family: 'gpt-5',
    status: 'stable',
    context: { combinedMax: 400_000 },
    modalities: { textIn: true, textOut: true },
    source: 'https://vercel.com/ai-gateway/models/gpt-5-mini',
    pricing: { inputPerMTokens: 0.25, outputPerMTokens: 2.0 },
    aliases: ['gpt5-mini', 'openai/gpt-5-mini'],
  },
  {
    id: 'openai:gpt-5-nano',
    provider: 'openai',
    vendorId: 'gpt-5-nano',
    displayName: 'GPT-5 nano',
    family: 'gpt-5',
    status: 'stable',
    context: { combinedMax: 400_000 },
    modalities: { textIn: true, textOut: true },
    source: 'https://vercel.com/ai-gateway/models/gpt-5-nano',
    pricing: { inputPerMTokens: 0.05, outputPerMTokens: 0.40 },
    aliases: ['gpt5-nano', 'openai/gpt-5-nano'],
  },
  {
    id: 'openai:gpt-4.1-mini',
    provider: 'openai',
    vendorId: 'gpt-4.1-mini',
    displayName: 'GPT-4.1 mini',
    family: 'gpt-4.1',
    status: 'stable',
    context: { combinedMax: 1_000_000 },
    modalities: { textIn: true, textOut: true },
    source: 'https://vercel.com/ai-gateway/models/gpt-4.1-mini',
    pricing: { inputPerMTokens: 0.40, outputPerMTokens: 1.60 },
    aliases: ['openai/gpt-4.1-mini', 'gpt-4_1-mini'],
  },
  {
    id: 'openai:gpt-4.1',
    provider: 'openai',
    vendorId: 'gpt-4.1',
    displayName: 'GPT-4.1',
    family: 'gpt-4.1',
    status: 'stable',
    context: { combinedMax: 1_000_000 },
    modalities: { textIn: true, textOut: true },
    source: 'https://vercel.com/ai-gateway/models/gpt-4.1',
    pricing: { inputPerMTokens: 2.0, outputPerMTokens: 8.0 },
    aliases: ['gpt-4_1', 'openai/gpt-4.1'],
  },
  {
    id: 'openai:gpt-4.1-nano',
    provider: 'openai',
    vendorId: 'gpt-4.1-nano',
    displayName: 'GPT-4.1 nano',
    family: 'gpt-4.1',
    status: 'stable',
    context: { combinedMax: 1_000_000 },
    modalities: { textIn: true, textOut: true },
    source: 'https://vercel.com/ai-gateway/models/gpt-4.1-nano',
    pricing: { inputPerMTokens: 0.10, outputPerMTokens: 0.40 },
    aliases: ['openai/gpt-4.1-nano', 'gpt-4_1-nano'],
  },
  {
    id: 'openai:gpt-4o',
    provider: 'openai',
    vendorId: 'gpt-4o',
    displayName: 'GPT-4o',
    family: 'gpt-4o',
    status: 'stable',
    context: { combinedMax: 128_000 },
    modalities: { textIn: true, textOut: true },
    source: 'https://vercel.com/ai-gateway/models/gpt-4o',
    pricing: { inputPerMTokens: 2.50, outputPerMTokens: 10.00 },
    aliases: ['openai/gpt-4o', 'gpt4o'],
  },
  {
    id: 'openai:text-embedding-3-small',
    provider: 'openai',
    vendorId: 'text-embedding-3-small',
    displayName: 'text-embedding-3-small',
    family: 'text-embedding',
    status: 'stable',
    context: {},
    modalities: { textIn: true, textOut: false },
    source: 'https://vercel.com/ai-gateway/models/text-embedding-3-small',
    pricing: { inputPerMTokens: 0.02 },
    aliases: ['openai/text-embedding-3-small'],
  },
] as const satisfies readonly Model[];
