export const nearaiModels = {
  id: "nearai",
  name: "NEAR AI Cloud",
  api: "https://cloud-api.near.ai/v1",
  npm: "@ai-sdk/openai-compatible",
  doc: "https://docs.near.ai/",
  env: ["NEARAI_API_KEY"],
  models: {
    "openai/whisper-large-v3": {
      id: "openai/whisper-large-v3",
      name: "Whisper Large v3",
      attachment: false,
      reasoning: false,
      temperature: false,
      tool_call: false,
      release_date: "2023-11-06",
      last_updated: "2023-11-06",
      modalities: {
        input: ["audio"],
        output: ["text"],
      },
      open_weights: true,
      cost: {
        input: 0.01,
        output: 0,
      },
      limit: {
        context: 448,
        output: 448,
      },
    },
    "openai/gpt-oss-120b": {
      id: "openai/gpt-oss-120b",
      name: "GPT-OSS 120B",
      attachment: false,
      reasoning: true,
      temperature: true,
      tool_call: true,
      release_date: "2025-08-05",
      last_updated: "2025-08-05",
      modalities: {
        input: ["text"],
        output: ["text"],
      },
      open_weights: true,
      cost: {
        input: 0.15,
        output: 0.55,
      },
      limit: {
        context: 131000,
        output: 32768,
      },
    },
    "zai-org/GLM-5.1-FP8": {
      id: "zai-org/GLM-5.1-FP8",
      name: "GLM-5.1 FP8",
      attachment: false,
      reasoning: true,
      temperature: true,
      tool_call: true,
      release_date: "2026-03-27",
      last_updated: "2026-03-27",
      modalities: {
        input: ["text"],
        output: ["text"],
      },
      open_weights: true,
      cost: {
        input: 0.85,
        output: 3.3,
      },
      limit: {
        context: 202752,
        output: 131072,
      },
    },
    "black-forest-labs/FLUX.2-klein-4B": {
      id: "black-forest-labs/FLUX.2-klein-4B",
      name: "FLUX.2 Klein 4B",
      attachment: false,
      reasoning: false,
      temperature: true,
      tool_call: false,
      release_date: "2026-01-14",
      last_updated: "2026-01-14",
      modalities: {
        input: ["text", "image"],
        output: ["image"],
      },
      open_weights: true,
      cost: {
        input: 1,
        output: 1,
      },
      limit: {
        context: 128000,
        output: 128000,
      },
    },
    "Qwen/Qwen3-30B-A3B-Instruct-2507": {
      id: "Qwen/Qwen3-30B-A3B-Instruct-2507",
      name: "Qwen3 30B-A3B Instruct 2507",
      attachment: false,
      reasoning: false,
      temperature: true,
      tool_call: true,
      release_date: "2025-07-29",
      last_updated: "2025-07-29",
      modalities: {
        input: ["text"],
        output: ["text"],
      },
      open_weights: true,
      cost: {
        input: 0.15,
        output: 0.55,
      },
      limit: {
        context: 262144,
        output: 32768,
      },
    },
    "Qwen/Qwen3-Embedding-0.6B": {
      id: "Qwen/Qwen3-Embedding-0.6B",
      name: "Qwen3 Embedding 0.6B",
      attachment: false,
      reasoning: false,
      temperature: false,
      tool_call: false,
      release_date: "2025-06-03",
      last_updated: "2025-06-03",
      modalities: {
        input: ["text"],
        output: ["text"],
      },
      open_weights: true,
      cost: {
        input: 0.01,
        output: 0,
      },
      limit: {
        context: 40960,
        output: 1024,
      },
    },
    "Qwen/Qwen3-Reranker-0.6B": {
      id: "Qwen/Qwen3-Reranker-0.6B",
      name: "Qwen3 Reranker 0.6B",
      attachment: false,
      reasoning: false,
      temperature: false,
      tool_call: false,
      release_date: "2025-06-03",
      last_updated: "2025-06-03",
      modalities: {
        input: ["text"],
        output: ["text"],
      },
      open_weights: true,
      cost: {
        input: 0.01,
        output: 0.01,
      },
      limit: {
        context: 40960,
        output: 1024,
      },
    },
    "Qwen/Qwen3-VL-30B-A3B-Instruct": {
      id: "Qwen/Qwen3-VL-30B-A3B-Instruct",
      name: "Qwen3-VL 30B-A3B Instruct",
      attachment: true,
      reasoning: false,
      temperature: true,
      tool_call: true,
      release_date: "2025-09-23",
      last_updated: "2025-09-23",
      modalities: {
        input: ["text", "image"],
        output: ["text"],
      },
      open_weights: true,
      cost: {
        input: 0.15,
        output: 0.55,
      },
      limit: {
        context: 256000,
        output: 32768,
      },
    },
    "openai/gpt-5.2": {
      id: "openai/gpt-5.2",
      name: "GPT-5.2",
      attachment: true,
      reasoning: true,
      temperature: false,
      tool_call: true,
      knowledge: "2025-08-31",
      release_date: "2025-12-11",
      last_updated: "2025-12-11",
      modalities: {
        input: ["text", "image"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 1.8,
        output: 15.5,
        cache_read: 0.18,
      },
      limit: {
        context: 400000,
        input: 272000,
        output: 128000,
      },
    },
    "openai/gpt-5.4-nano": {
      id: "openai/gpt-5.4-nano",
      name: "GPT-5.4 nano",
      attachment: true,
      reasoning: true,
      temperature: false,
      tool_call: true,
      knowledge: "2025-08-31",
      release_date: "2026-03-17",
      last_updated: "2026-03-17",
      modalities: {
        input: ["text", "image"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 0.2,
        output: 1.25,
        cache_read: 0.02,
      },
      limit: {
        context: 400000,
        input: 272000,
        output: 128000,
      },
    },
    "openai/gpt-4.1": {
      id: "openai/gpt-4.1",
      name: "GPT-4.1",
      attachment: true,
      reasoning: false,
      temperature: true,
      tool_call: true,
      knowledge: "2024-04",
      release_date: "2025-04-14",
      last_updated: "2025-04-14",
      modalities: {
        input: ["text", "image", "pdf"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 2,
        output: 8,
        cache_read: 0.5,
      },
      limit: {
        context: 1047576,
        output: 32768,
      },
    },
    "openai/gpt-4.1-mini": {
      id: "openai/gpt-4.1-mini",
      name: "GPT-4.1 mini",
      attachment: true,
      reasoning: false,
      temperature: true,
      tool_call: true,
      knowledge: "2024-04",
      release_date: "2025-04-14",
      last_updated: "2025-04-14",
      modalities: {
        input: ["text", "image", "pdf"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 0.4,
        output: 1.6,
        cache_read: 0.1,
      },
      limit: {
        context: 1047576,
        output: 32768,
      },
    },
    "openai/gpt-5.1": {
      id: "openai/gpt-5.1",
      name: "GPT-5.1",
      attachment: true,
      reasoning: true,
      temperature: false,
      tool_call: true,
      knowledge: "2024-09-30",
      release_date: "2025-11-13",
      last_updated: "2025-11-13",
      modalities: {
        input: ["text", "image"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 1.25,
        output: 10,
        cache_read: 0.13,
      },
      limit: {
        context: 400000,
        input: 272000,
        output: 128000,
      },
    },
    "openai/gpt-5-nano": {
      id: "openai/gpt-5-nano",
      name: "GPT-5 Nano",
      attachment: true,
      reasoning: true,
      temperature: false,
      tool_call: true,
      knowledge: "2024-05-30",
      release_date: "2025-08-07",
      last_updated: "2025-08-07",
      modalities: {
        input: ["text", "image"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 0.05,
        output: 0.4,
        cache_read: 0.005,
      },
      limit: {
        context: 400000,
        input: 272000,
        output: 128000,
      },
    },
    "openai/gpt-5.4": {
      id: "openai/gpt-5.4",
      name: "GPT-5.4",
      attachment: true,
      reasoning: true,
      temperature: false,
      tool_call: true,
      knowledge: "2025-08-31",
      release_date: "2026-03-05",
      last_updated: "2026-03-05",
      modalities: {
        input: ["text", "image", "pdf"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 2.5,
        output: 15,
        cache_read: 0.25,
        context_over_200k: {
          input: 5,
          output: 22.5,
          cache_read: 0.5,
        },
        tiers: [
          {
            input: 5,
            output: 22.5,
            cache_read: 0.5,
            tier: {
              type: "context",
              size: 272000,
            },
          },
        ],
      },
      limit: {
        context: 1050000,
        input: 922000,
        output: 128000,
      },
    },
    "openai/gpt-5.4-mini": {
      id: "openai/gpt-5.4-mini",
      name: "GPT-5.4 mini",
      attachment: true,
      reasoning: true,
      temperature: false,
      tool_call: true,
      knowledge: "2025-08-31",
      release_date: "2026-03-17",
      last_updated: "2026-03-17",
      modalities: {
        input: ["text", "image"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 0.75,
        output: 4.5,
        cache_read: 0.075,
      },
      limit: {
        context: 400000,
        input: 272000,
        output: 128000,
      },
    },
    "openai/gpt-5.5": {
      id: "openai/gpt-5.5",
      name: "GPT-5.5",
      attachment: true,
      reasoning: true,
      temperature: false,
      tool_call: true,
      knowledge: "2025-12-01",
      release_date: "2026-04-23",
      last_updated: "2026-04-23",
      modalities: {
        input: ["text", "image", "pdf"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 5,
        output: 30,
        cache_read: 0.5,
        context_over_200k: {
          input: 10,
          output: 45,
          cache_read: 1,
        },
        tiers: [
          {
            input: 10,
            output: 45,
            cache_read: 1,
            tier: {
              type: "context",
              size: 272000,
            },
          },
        ],
      },
      limit: {
        context: 1050000,
        input: 922000,
        output: 128000,
      },
    },
    "openai/gpt-4.1-nano": {
      id: "openai/gpt-4.1-nano",
      name: "GPT-4.1 nano",
      attachment: true,
      reasoning: false,
      temperature: true,
      tool_call: true,
      knowledge: "2024-04",
      release_date: "2025-04-14",
      last_updated: "2025-04-14",
      modalities: {
        input: ["text", "image"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 0.1,
        output: 0.4,
        cache_read: 0.03,
      },
      limit: {
        context: 1047576,
        output: 32768,
      },
    },
    "openai/o4-mini": {
      id: "openai/o4-mini",
      name: "o4-mini",
      attachment: true,
      reasoning: true,
      temperature: false,
      tool_call: true,
      knowledge: "2024-05",
      release_date: "2025-04-16",
      last_updated: "2025-04-16",
      modalities: {
        input: ["text", "image"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 1.1,
        output: 4.4,
        cache_read: 0.28,
      },
      limit: {
        context: 200000,
        output: 100000,
      },
    },
    "openai/gpt-5-mini": {
      id: "openai/gpt-5-mini",
      name: "GPT-5 Mini",
      attachment: true,
      reasoning: true,
      temperature: false,
      tool_call: true,
      knowledge: "2024-05-30",
      release_date: "2025-08-07",
      last_updated: "2025-08-07",
      modalities: {
        input: ["text", "image"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 0.25,
        output: 2,
        cache_read: 0.025,
      },
      limit: {
        context: 400000,
        input: 272000,
        output: 128000,
      },
    },
    "openai/o3-mini": {
      id: "openai/o3-mini",
      name: "o3-mini",
      attachment: false,
      reasoning: true,
      temperature: false,
      tool_call: true,
      knowledge: "2024-05",
      release_date: "2024-12-20",
      last_updated: "2025-01-29",
      modalities: {
        input: ["text"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 1.1,
        output: 4.4,
        cache_read: 0.55,
      },
      limit: {
        context: 200000,
        output: 100000,
      },
    },
    "openai/o3": {
      id: "openai/o3",
      name: "o3",
      attachment: true,
      reasoning: true,
      temperature: false,
      tool_call: true,
      knowledge: "2024-05",
      release_date: "2025-04-16",
      last_updated: "2025-04-16",
      modalities: {
        input: ["text", "image", "pdf"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 2,
        output: 8,
        cache_read: 0.5,
      },
      limit: {
        context: 200000,
        output: 100000,
      },
    },
    "openai/gpt-5": {
      id: "openai/gpt-5",
      name: "GPT-5",
      attachment: true,
      reasoning: true,
      temperature: false,
      tool_call: true,
      knowledge: "2024-09-30",
      release_date: "2025-08-07",
      last_updated: "2025-08-07",
      modalities: {
        input: ["text", "image"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 1.25,
        output: 10,
        cache_read: 0.125,
      },
      limit: {
        context: 400000,
        input: 272000,
        output: 128000,
      },
    },
    "anthropic/claude-haiku-4-5": {
      id: "anthropic/claude-haiku-4-5",
      name: "Claude Haiku 4.5 (latest)",
      attachment: true,
      reasoning: true,
      temperature: true,
      tool_call: true,
      knowledge: "2025-02-28",
      release_date: "2025-10-15",
      last_updated: "2025-10-15",
      modalities: {
        input: ["text", "image", "pdf"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 1,
        output: 5,
        cache_read: 0.1,
        cache_write: 1.25,
      },
      limit: {
        context: 200000,
        output: 64000,
      },
    },
    "anthropic/claude-sonnet-4-5": {
      id: "anthropic/claude-sonnet-4-5",
      name: "Claude Sonnet 4.5 (latest)",
      attachment: true,
      reasoning: true,
      temperature: true,
      tool_call: true,
      knowledge: "2025-07-31",
      release_date: "2025-09-29",
      last_updated: "2025-09-29",
      modalities: {
        input: ["text", "image", "pdf"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 3,
        output: 15.5,
        cache_read: 0.3,
        cache_write: 3.75,
      },
      limit: {
        context: 200000,
        output: 64000,
      },
    },
    "anthropic/claude-sonnet-4-6": {
      id: "anthropic/claude-sonnet-4-6",
      name: "Claude Sonnet 4.6",
      attachment: true,
      reasoning: true,
      temperature: true,
      tool_call: true,
      knowledge: "2025-08-31",
      release_date: "2026-02-17",
      last_updated: "2026-03-13",
      modalities: {
        input: ["text", "image", "pdf"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 3,
        output: 15,
        cache_read: 0.3,
        cache_write: 3.75,
      },
      limit: {
        context: 1000000,
        output: 64000,
      },
    },
    "anthropic/claude-opus-4-7": {
      id: "anthropic/claude-opus-4-7",
      name: "Claude Opus 4.7",
      attachment: true,
      reasoning: true,
      temperature: false,
      tool_call: true,
      knowledge: "2026-01-31",
      release_date: "2026-04-16",
      last_updated: "2026-04-16",
      modalities: {
        input: ["text", "image", "pdf"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 5,
        output: 25,
        cache_read: 0.5,
        cache_write: 6.25,
      },
      limit: {
        context: 1000000,
        output: 128000,
      },
    },
    "anthropic/claude-opus-4-6": {
      id: "anthropic/claude-opus-4-6",
      name: "Claude Opus 4.6",
      attachment: true,
      reasoning: true,
      temperature: true,
      tool_call: true,
      knowledge: "2025-05-31",
      release_date: "2026-02-05",
      last_updated: "2026-03-13",
      modalities: {
        input: ["text", "image", "pdf"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 5,
        output: 25,
        cache_read: 0.5,
        cache_write: 6.25,
      },
      limit: {
        context: 200000,
        output: 128000,
      },
    },
    "google/gemini-3.1-flash-lite": {
      id: "google/gemini-3.1-flash-lite",
      name: "Gemini 3.1 Flash Lite",
      attachment: true,
      reasoning: true,
      temperature: true,
      tool_call: true,
      knowledge: "2025-01",
      release_date: "2026-05-07",
      last_updated: "2026-05-07",
      modalities: {
        input: ["text", "image", "video", "audio", "pdf"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 0.25,
        output: 1.5,
        cache_read: 0.025,
        input_audio: 0.5,
      },
      limit: {
        context: 1048576,
        output: 65536,
      },
    },
    "google/gemini-2.5-pro": {
      id: "google/gemini-2.5-pro",
      name: "Gemini 2.5 Pro",
      attachment: true,
      reasoning: true,
      temperature: true,
      tool_call: true,
      knowledge: "2025-01",
      release_date: "2025-03-20",
      last_updated: "2025-06-05",
      modalities: {
        input: ["text", "image", "audio", "video", "pdf"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 1.25,
        output: 10,
        cache_read: 0.125,
        context_over_200k: {
          input: 2.5,
          output: 15,
          cache_read: 0.25,
        },
        tiers: [
          {
            input: 2.5,
            output: 15,
            cache_read: 0.25,
            tier: {
              type: "context",
              size: 200000,
            },
          },
        ],
      },
      limit: {
        context: 1048576,
        output: 65536,
      },
    },
    "google/gemini-2.5-flash-lite": {
      id: "google/gemini-2.5-flash-lite",
      name: "Gemini 2.5 Flash-Lite",
      attachment: true,
      reasoning: true,
      temperature: true,
      tool_call: true,
      knowledge: "2025-01",
      release_date: "2025-06-17",
      last_updated: "2025-06-17",
      modalities: {
        input: ["text", "image", "audio", "video", "pdf"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 0.1,
        output: 0.4,
        cache_read: 0.01,
        input_audio: 0.3,
      },
      limit: {
        context: 1048576,
        output: 65536,
      },
    },
    "google/gemini-2.5-flash": {
      id: "google/gemini-2.5-flash",
      name: "Gemini 2.5 Flash",
      attachment: true,
      reasoning: true,
      temperature: true,
      tool_call: true,
      knowledge: "2025-01",
      release_date: "2025-03-20",
      last_updated: "2025-06-05",
      modalities: {
        input: ["text", "image", "audio", "video", "pdf"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 0.3,
        output: 2.5,
        cache_read: 0.03,
        input_audio: 1,
      },
      limit: {
        context: 1048576,
        output: 65536,
      },
    },
    "Qwen/Qwen3.5-122B-A10B": {
      id: "Qwen/Qwen3.5-122B-A10B",
      name: "Qwen3.5 122B-A10B",
      attachment: true,
      reasoning: true,
      temperature: true,
      tool_call: true,
      release_date: "2026-02-23",
      last_updated: "2026-02-23",
      modalities: {
        input: ["text"],
        output: ["text"],
      },
      open_weights: true,
      cost: {
        input: 0.4,
        output: 3.2,
      },
      limit: {
        context: 131072,
        output: 32768,
      },
    },
  },
} as const;
export default nearaiModels;
