// Auto-generated by scripts/sync-models-dev.mjs
import alibabaProvider from "./providers/alibaba.js";
import alibaba_cnProvider from "./providers/alibaba-cn.js";
import amazon_bedrockProvider from "./providers/amazon-bedrock.js";
import anthropicProvider from "./providers/anthropic.js";
import azureProvider from "./providers/azure.js";
import basetenProvider from "./providers/baseten.js";
import cerebrasProvider from "./providers/cerebras.js";
import chutesProvider from "./providers/chutes.js";
import cloudflare_workers_aiProvider from "./providers/cloudflare-workers-ai.js";
import cortecsProvider from "./providers/cortecs.js";
import deepinfraProvider from "./providers/deepinfra.js";
import deepseekProvider from "./providers/deepseek.js";
import fastrouterProvider from "./providers/fastrouter.js";
import fireworks_aiProvider from "./providers/fireworks-ai.js";
import github_copilotProvider from "./providers/github-copilot.js";
import github_modelsProvider from "./providers/github-models.js";
import googleProvider from "./providers/google.js";
import google_vertexProvider from "./providers/google-vertex.js";
import google_vertex_anthropicProvider from "./providers/google-vertex-anthropic.js";
import groqProvider from "./providers/groq.js";
import huggingfaceProvider from "./providers/huggingface.js";
import inceptionProvider from "./providers/inception.js";
import inferenceProvider from "./providers/inference.js";
import llamaProvider from "./providers/llama.js";
import lmstudioProvider from "./providers/lmstudio.js";
import lucidqueryProvider from "./providers/lucidquery.js";
import mistralProvider from "./providers/mistral.js";
import modelscopeProvider from "./providers/modelscope.js";
import moonshotaiProvider from "./providers/moonshotai.js";
import moonshotai_cnProvider from "./providers/moonshotai-cn.js";
import morphProvider from "./providers/morph.js";
import nvidiaProvider from "./providers/nvidia.js";
import openaiProvider from "./providers/openai.js";
import opencodeProvider from "./providers/opencode.js";
import openrouterProvider from "./providers/openrouter.js";
import perplexityProvider from "./providers/perplexity.js";
import requestyProvider from "./providers/requesty.js";
import submodelProvider from "./providers/submodel.js";
import syntheticProvider from "./providers/synthetic.js";
import togetheraiProvider from "./providers/togetherai.js";
import upstageProvider from "./providers/upstage.js";
import v0Provider from "./providers/v0.js";
import veniceProvider from "./providers/venice.js";
import vercelProvider from "./providers/vercel.js";
import wandbProvider from "./providers/wandb.js";
import xaiProvider from "./providers/xai.js";
import zaiProvider from "./providers/zai.js";
import zai_coding_planProvider from "./providers/zai-coding-plan.js";
import zhipuaiProvider from "./providers/zhipuai.js";
import zhipuai_coding_planProvider from "./providers/zhipuai-coding-plan.js";

export const modelsdevProviders = {
  alibaba: alibabaProvider,
  "alibaba-cn": alibaba_cnProvider,
  "amazon-bedrock": amazon_bedrockProvider,
  anthropic: anthropicProvider,
  azure: azureProvider,
  baseten: basetenProvider,
  cerebras: cerebrasProvider,
  chutes: chutesProvider,
  "cloudflare-workers-ai": cloudflare_workers_aiProvider,
  cortecs: cortecsProvider,
  deepinfra: deepinfraProvider,
  deepseek: deepseekProvider,
  fastrouter: fastrouterProvider,
  "fireworks-ai": fireworks_aiProvider,
  "github-copilot": github_copilotProvider,
  "github-models": github_modelsProvider,
  google: googleProvider,
  "google-vertex": google_vertexProvider,
  "google-vertex-anthropic": google_vertex_anthropicProvider,
  groq: groqProvider,
  huggingface: huggingfaceProvider,
  inception: inceptionProvider,
  inference: inferenceProvider,
  llama: llamaProvider,
  lmstudio: lmstudioProvider,
  lucidquery: lucidqueryProvider,
  mistral: mistralProvider,
  modelscope: modelscopeProvider,
  moonshotai: moonshotaiProvider,
  "moonshotai-cn": moonshotai_cnProvider,
  morph: morphProvider,
  nvidia: nvidiaProvider,
  openai: openaiProvider,
  opencode: opencodeProvider,
  openrouter: openrouterProvider,
  perplexity: perplexityProvider,
  requesty: requestyProvider,
  submodel: submodelProvider,
  synthetic: syntheticProvider,
  togetherai: togetheraiProvider,
  upstage: upstageProvider,
  v0: v0Provider,
  venice: veniceProvider,
  vercel: vercelProvider,
  wandb: wandbProvider,
  xai: xaiProvider,
  zai: zaiProvider,
  "zai-coding-plan": zai_coding_planProvider,
  zhipuai: zhipuaiProvider,
  "zhipuai-coding-plan": zhipuai_coding_planProvider,
} as const;
