export const cortecsProvider = {
  id: "cortecs",
  name: "Cortecs",
  api: "https://api.cortecs.ai/v1",
  npm: "@ai-sdk/openai-compatible",
  doc: "https://api.cortecs.ai/v1/models",
  env: ["CORTECS_API_KEY"],
  source: "models.dev",
  schemaVersion: 1,
  models: {
    "gemini-2.5-pro": {
      id: "gemini-2.5-pro",
      name: "Gemini 2.5 Pro",
      attachment: false,
      reasoning: false,
      temperature: true,
      tool_call: true,
      knowledge: "2025-01",
      release_date: "2025-03-20",
      last_updated: "2025-06-17",
      modalities: {
        input: ["text", "image"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 1.3416,
        output: 8.944,
      },
      limit: {
        context: 1048576,
        output: 65535,
      },
    },
    "claude-sonnet-4": {
      id: "claude-sonnet-4",
      name: "Claude Sonnet 4",
      attachment: false,
      reasoning: false,
      temperature: true,
      tool_call: true,
      knowledge: "2025-03",
      release_date: "2025-05-22",
      last_updated: "2025-05-22",
      modalities: {
        input: ["text", "image"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 2.683,
        output: 13.416,
      },
      limit: {
        context: 200000,
        output: 64000,
      },
    },
    "gpt-4.1": {
      id: "gpt-4.1",
      name: "GPT 4.1",
      attachment: false,
      reasoning: false,
      temperature: true,
      tool_call: true,
      knowledge: "2024-06",
      release_date: "2025-04-14",
      last_updated: "2025-04-14",
      modalities: {
        input: ["text", "image"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 1.91,
        output: 7.64,
      },
      limit: {
        context: 1047576,
        output: 32768,
      },
    },
    "qwen3-32b": {
      id: "qwen3-32b",
      name: "Qwen3 32B",
      attachment: false,
      reasoning: false,
      temperature: true,
      tool_call: true,
      knowledge: "2024-12",
      release_date: "2025-04-29",
      last_updated: "2025-04-29",
      modalities: {
        input: ["text"],
        output: ["text"],
      },
      open_weights: true,
      cost: {
        input: 0.08,
        output: 0.268,
      },
      limit: {
        context: 16384,
        output: 16384,
      },
    },
    "deepseek-v3-0324": {
      id: "deepseek-v3-0324",
      name: "DeepSeek V3 0324",
      attachment: false,
      reasoning: false,
      temperature: true,
      tool_call: true,
      knowledge: "2024-07",
      release_date: "2025-03-24",
      last_updated: "2025-03-24",
      modalities: {
        input: ["text"],
        output: ["text"],
      },
      open_weights: true,
      cost: {
        input: 0.447,
        output: 1.342,
      },
      limit: {
        context: 128000,
        output: 128000,
      },
    },
    "llama-3.1-405b-instruct": {
      id: "llama-3.1-405b-instruct",
      name: "Llama 3.1 405B Instruct",
      attachment: false,
      reasoning: false,
      temperature: true,
      tool_call: true,
      knowledge: "2023-12",
      release_date: "2024-07-23",
      last_updated: "2024-07-23",
      modalities: {
        input: ["text"],
        output: ["text"],
      },
      open_weights: true,
      cost: {
        input: 0,
        output: 0,
      },
      limit: {
        context: 128000,
        output: 128000,
      },
    },
    "qwen3-coder-480b-a35b-instruct": {
      id: "qwen3-coder-480b-a35b-instruct",
      name: "Qwen3 Coder 480B A35B Instruct",
      attachment: false,
      reasoning: false,
      temperature: true,
      tool_call: true,
      knowledge: "2025-01",
      release_date: "2025-07-25",
      last_updated: "2025-07-25",
      modalities: {
        input: ["text"],
        output: ["text"],
      },
      open_weights: true,
      cost: {
        input: 0.358,
        output: 1.61,
      },
      limit: {
        context: 262000,
        output: 262000,
      },
    },
    "kimi-k2-instruct": {
      id: "kimi-k2-instruct",
      name: "Kimi K2 Instruct",
      attachment: false,
      reasoning: false,
      temperature: true,
      tool_call: true,
      knowledge: "2024-07",
      release_date: "2025-07-11",
      last_updated: "2025-09-05",
      modalities: {
        input: ["text"],
        output: ["text"],
      },
      open_weights: true,
      cost: {
        input: 0.447,
        output: 2.147,
      },
      limit: {
        context: 131000,
        output: 131000,
      },
    },
    "gpt-oss-120b": {
      id: "gpt-oss-120b",
      name: "GPT Oss 120b",
      attachment: false,
      reasoning: false,
      temperature: true,
      tool_call: true,
      knowledge: "2024-01",
      release_date: "2025-08-05",
      last_updated: "2025-08-05",
      modalities: {
        input: ["text"],
        output: ["text"],
      },
      open_weights: true,
      cost: {
        input: 0,
        output: 0,
      },
      limit: {
        context: 128000,
        output: 128000,
      },
    },
    "nova-pro-v1": {
      id: "nova-pro-v1",
      name: "Nova Pro 1.0",
      attachment: false,
      reasoning: false,
      temperature: true,
      tool_call: true,
      knowledge: "2024-04",
      release_date: "2024-12-03",
      last_updated: "2024-12-03",
      modalities: {
        input: ["text", "image"],
        output: ["text"],
      },
      open_weights: false,
      cost: {
        input: 0.824,
        output: 3.295,
      },
      limit: {
        context: 300000,
        output: 5000,
      },
    },
  },
} as const;
export default cortecsProvider;
