// Auto-generated by scripts/sync-openrouter.mjs
import agentica_orgProvider from "./providers/agentica-org.js";
import ai21Provider from "./providers/ai21.js";
import aion_labsProvider from "./providers/aion-labs.js";
import alfredprosProvider from "./providers/alfredpros.js";
import alibabaProvider from "./providers/alibaba.js";
import allenaiProvider from "./providers/allenai.js";
import alpindaleProvider from "./providers/alpindale.js";
import amazonProvider from "./providers/amazon.js";
import anthracite_orgProvider from "./providers/anthracite-org.js";
import anthropicProvider from "./providers/anthropic.js";
import arcee_aiProvider from "./providers/arcee-ai.js";
import arliaiProvider from "./providers/arliai.js";
import baiduProvider from "./providers/baidu.js";
import bytedanceProvider from "./providers/bytedance.js";
import cognitivecomputationsProvider from "./providers/cognitivecomputations.js";
import cohereProvider from "./providers/cohere.js";
import deepcogitoProvider from "./providers/deepcogito.js";
import deepseekProvider from "./providers/deepseek.js";
import eleutheraiProvider from "./providers/eleutherai.js";
import googleProvider from "./providers/google.js";
import grypheProvider from "./providers/gryphe.js";
import inceptionProvider from "./providers/inception.js";
import inflectionProvider from "./providers/inflection.js";
import liquidProvider from "./providers/liquid.js";
import mancerProvider from "./providers/mancer.js";
import meituanProvider from "./providers/meituan.js";
import meta_llamaProvider from "./providers/meta-llama.js";
import microsoftProvider from "./providers/microsoft.js";
import minimaxProvider from "./providers/minimax.js";
import mistralaiProvider from "./providers/mistralai.js";
import moonshotaiProvider from "./providers/moonshotai.js";
import morphProvider from "./providers/morph.js";
import neversleepProvider from "./providers/neversleep.js";
import nousresearchProvider from "./providers/nousresearch.js";
import nvidiaProvider from "./providers/nvidia.js";
import openaiProvider from "./providers/openai.js";
import opengvlabProvider from "./providers/opengvlab.js";
import openrouterProvider from "./providers/openrouter.js";
import perplexityProvider from "./providers/perplexity.js";
import qwenProvider from "./providers/qwen.js";
import raifleProvider from "./providers/raifle.js";
import sao10kProvider from "./providers/sao10k.js";
import shisa_aiProvider from "./providers/shisa-ai.js";
import stepfun_aiProvider from "./providers/stepfun-ai.js";
import switchpointProvider from "./providers/switchpoint.js";
import tencentProvider from "./providers/tencent.js";
import thedrummerProvider from "./providers/thedrummer.js";
import thudmProvider from "./providers/thudm.js";
import tngtechProvider from "./providers/tngtech.js";
import undi95Provider from "./providers/undi95.js";
import x_aiProvider from "./providers/x-ai.js";
import z_aiProvider from "./providers/z-ai.js";

export const openrouterProviders = {
  "agentica-org": agentica_orgProvider,
  ai21: ai21Provider,
  "aion-labs": aion_labsProvider,
  alfredpros: alfredprosProvider,
  alibaba: alibabaProvider,
  allenai: allenaiProvider,
  alpindale: alpindaleProvider,
  amazon: amazonProvider,
  "anthracite-org": anthracite_orgProvider,
  anthropic: anthropicProvider,
  "arcee-ai": arcee_aiProvider,
  arliai: arliaiProvider,
  baidu: baiduProvider,
  bytedance: bytedanceProvider,
  cognitivecomputations: cognitivecomputationsProvider,
  cohere: cohereProvider,
  deepcogito: deepcogitoProvider,
  deepseek: deepseekProvider,
  eleutherai: eleutheraiProvider,
  google: googleProvider,
  gryphe: grypheProvider,
  inception: inceptionProvider,
  inflection: inflectionProvider,
  liquid: liquidProvider,
  mancer: mancerProvider,
  meituan: meituanProvider,
  "meta-llama": meta_llamaProvider,
  microsoft: microsoftProvider,
  minimax: minimaxProvider,
  mistralai: mistralaiProvider,
  moonshotai: moonshotaiProvider,
  morph: morphProvider,
  neversleep: neversleepProvider,
  nousresearch: nousresearchProvider,
  nvidia: nvidiaProvider,
  openai: openaiProvider,
  opengvlab: opengvlabProvider,
  openrouter: openrouterProvider,
  perplexity: perplexityProvider,
  qwen: qwenProvider,
  raifle: raifleProvider,
  sao10k: sao10kProvider,
  "shisa-ai": shisa_aiProvider,
  "stepfun-ai": stepfun_aiProvider,
  switchpoint: switchpointProvider,
  tencent: tencentProvider,
  thedrummer: thedrummerProvider,
  thudm: thudmProvider,
  tngtech: tngtechProvider,
  undi95: undi95Provider,
  "x-ai": x_aiProvider,
  "z-ai": z_aiProvider,
} as const;
